[package]
name = "cross_chain_v3"
version = "1.0.0"
authors = ["cross_chain_dev"]

[addresses]
cross_chain = "0xba916e9cbf294e552e4281dfc227fadbd3413d81c2fc233816f85dd89d53f54c"

# Circle CCTP官方包地址（来自all.md文档）
message_transmitter = "0x081e86cebf457a0c6004f35bd648a2794698f52e0dde09a48619dcd3d4cc23d9"
token_messenger_minter = "0x5f9b937419dda90aa06c1836b7847f65bbbe3f1217567758dc2488be31a477b9"

# Hyperion DEX 地址（测试网）
hyperion_dex = "0x3673bee9e7b78ae63d4a9e3d58425bc97e7f3b8d68efc846ee732b14369333dd"
dex_contract = "0x3673bee9e7b78ae63d4a9e3d58425bc97e7f3b8d68efc846ee732b14369333dd"
deployer = "0x3673bee9e7b78ae63d4a9e3d58425bc97e7f3b8d68efc846ee732b14369333dd"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-stdlib" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/move-stdlib" }

# Hyperion DEX 依赖 (本地路径)
dex = { local = "../hyperion-interface" }

[dev-dependencies]